name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check style
        run: mvn git-code-format:validate-code-format
      - name: Unit tests
        run: mvn test
